# Generated by Django 5.1 on 2024-09-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=50)),
                ('no_family_memebers', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_committee', models.BooleanField(default=False)),
                ('is_resident', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=20)),
                ('gateno_duty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('cuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to='accounts.commonuser')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to='accounts.commonuser')),
            ],
        ),
    ]
