# Generated by Django 5.1 on 2024-09-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_commonuser_groups_commonuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='no_family_memebers',
        ),
    ]
