# Generated by Django 5.1 on 2024-09-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_commonuser_no_family_memebers'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='no_family_memebers',
            field=models.BigIntegerField(default=0),
        ),
    ]
